# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Badge_Tester

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:

  badges:
    runs-on: ubuntu-latest

    steps:
    # Actions
    - name: Test Lint and Badge
      run: |
        echo "### Test" >> Testing.md
    # Auto-Commit Badge Changes
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Adding Badges. Testdetails in #${{ github.event.pull_request.number }}"
